#!/bin/bash

# output colors:
# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux

if [[ -t 1 ]]; then
	export red=$(tput setaf 1)
	export green=$(tput setaf 2)
	export yellow=$(tput setaf 3)
	export normal=$(tput sgr0)
else
	export red=
	export green=
	export yellow=
	export normal=
fi

SCRIPT_HERE=$(dirname $0)
. $SCRIPT_HERE/functions
SCRIPT_ARGS="$@"

process_args "$@"

read_upper_config() {
	# Read any config file found in directories above this one
	echo -n
}

read_upper_config

pushd "." > /dev/null
	init_summary
	test_dir $(basename $(pwd -P))

	[[ -z "$noSummary" ]] && display_summary
popd > /dev/null

